from pathlib import Path
from src.constants import *

##get root dir
ROOT = Path.cwd()
#ROOT = FILE.parent

#image
IMAGE_DIR = ROOT / IMAGE_DIR_NAME

DETECTED_IMAGE_DIR = IMAGE_DIR / DETECTED_IMAGE
NON_DETECTED_IMAGE_DIR = IMAGE_DIR / NON_DETECTED_IMAGE


# Videos
VIDEO_DIR = ROOT / VIDEO_DIR_NAME

FIRST_VIDEO_DIR = VIDEO_DIR / FIRST_VIDEO
SECOND_VIDEO_DIR = VIDEO_DIR / SECOND_VIDEO
THURD_VIDEO_DIR = VIDEO_DIR / THURD_VIDEO

VIDEOS_DICT = {
    'video_1': FIRST_VIDEO_DIR,
    'video_2': SECOND_VIDEO_DIR,
    'video_3': THURD_VIDEO_DIR,
}

# Weights
WEIGHT_DIR = ROOT / WEIGHT_DIR_NAME

YOLO_MODEL_CLS_DIR = WEIGHT_DIR / YOLO_MODEL_CLS
YOLO_MODEL_SEG_DIR = WEIGHT_DIR / YOLO_MODEL_SEG
YOLO_MODEL_DIR = WEIGHT_DIR / YOLO_MODEL

print(YOLO_MODEL_CLS_DIR)